### ISSUE TITLE
Incorrect reference to tyk-pro in tyk-headless chart when mounting secrets

### ISSUE THREAD

**Issue by elliothill** [TykTechnologies/tyk-helm-chart#179] opened 2021-11-30 23:40 UTC
Hi!

I'm currently using the tyk-headless chart to deploy Tyk-CE, and am attempting to mount a policies.json file via a secret. Unfortunately, when running the tyk-headless chart, the following error is encountered:

![image](https://user-images.githubusercontent.com/15995619/144144226-94d17c23-1ef8-4d15-be66-ffe469353e69.png)

Looking at the secrets-mount.yaml file specified, it has references to tyk-pro rather than tyk-headless.

**Comment by elliothill** [comment] 2021-12-01 01:46
Another item to note: Any mounts specified in the tyk-headless values.yaml file are only mounted in the init-container, not in the actual gateway, and thus cannot be used.

**Comment by cherrymu** [comment] 2021-12-01 09:06
Hello @elliothill I couldn't reproduce the first issue as the installation went perfectly alright with tyk-headless with mounts specified in the values.yaml file. So, I recommend you to clone the repo on your local system, a pretty neat fresh one and try to reproduce again using the fresh cloned charts. 

Regarding the next issue, you are right that the secret mounting should be done with the main container rather than a init container which renders the things null as it will be gone once the main container is fully initialised.

**Comment by cherrymu** [comment] 2022-02-02 05:35
Closing this issue since it is fixed in the [pull](https://github.com/TykTechnologies/tyk-helm-chart/pull/180).

**Closed by cherrymu** 2022-02-02 05:35 UTC
